sudo: required
services:
  - docker

before_install:
  - docker build -t arma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arma/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-701321592228"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_KEY"
